# PUNTO A



In [1]:
n = int(input("Ingrese la longitud de los vectores: "))


vector1 = []
vector2 = []

for i in range(n):
    valor1 = float(input(f"Ingrese el valor {i+1} del primer vector: "))
    vector1.append(valor1)
    valor2 = float(input(f"Ingrese el valor {i+1} del segundo vector: "))
    vector2.append(valor2)


producto_escalar = 0
for i in range(n):
    producto_escalar += vector1[i] * vector2[i]

# Imprimir el resultado
print(f"El producto escalar de los vectores {vector1} y {vector2} es {producto_escalar}.")

Ingrese la longitud de los vectores: 5
Ingrese el valor 1 del primer vector: 3
Ingrese el valor 1 del segundo vector: 6
Ingrese el valor 2 del primer vector: 4
Ingrese el valor 2 del segundo vector: -7
Ingrese el valor 3 del primer vector: -5
Ingrese el valor 3 del segundo vector: 3
Ingrese el valor 4 del primer vector: 6
Ingrese el valor 4 del segundo vector: -9
Ingrese el valor 5 del primer vector: 21
Ingrese el valor 5 del segundo vector: -9
El producto escalar de los vectores [3.0, 4.0, -5.0, 6.0, 21.0] y [6.0, -7.0, 3.0, -9.0, -9.0] es -268.0.


#PUNTO B

In [2]:
import numpy as np


m = int(input("Ingrese el número de filas de la matriz A: "))
n = int(input("Ingrese el número de columnas de la matriz A: "))
mb = int(input("Ingrese el número de filas de la matriz B: "))
nb = int(input("Ingrese el número de columnas de la matriz B: "))

if n != mb:
    print("No se puede realizar la operación B x A.")
    exit()

print("Ingrese los elementos de la matriz A: ")
A = np.zeros((m,n)) 
for i in range(m):
    for j in range(n):
        A[i,j] = float(input(f"A[{i+1},{j+1}]: "))


print("Ingrese los elementos de la matriz B: ")
B = np.zeros((mb,nb)) 
for i in range(mb):
    for j in range(nb):
        B[i,j] = float(input(f"B[{i+1},{j+1}]: "))


print("3A = ")
print(3*A)

print("4B = ")
print(4*B)

print("A + B = ")
print(A + B)

print("B × A = ")
print(np.dot(B,A))

Ingrese el número de filas de la matriz A: 1
Ingrese el número de columnas de la matriz A: 2
Ingrese el número de filas de la matriz B: 2
Ingrese el número de columnas de la matriz B: 1
Ingrese los elementos de la matriz A: 
A[1,1]: 4
A[1,2]: 7
Ingrese los elementos de la matriz B: 
B[1,1]: 2
B[2,1]: 5
3A = 
[[12. 21.]]
4B = 
[[ 8.]
 [20.]]
A + B = 
[[ 6.  9.]
 [ 9. 12.]]
B × A = 
[[ 8. 14.]
 [20. 35.]]


In [5]:
arreglo2d = np.arange(25).reshape(5,5)
print(arreglo2d)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
